cpi {
	events {
		CY = cycles:u
		IN = instructions:u
	}

	cpi = CY / IN

	print cpi
}

branch {
	events {
		IN = instructions:u
		BI = branch-instructions:u
		BM = branch-misses:u
	}

	branch-rate       = BI / IN
	branch-miss-rate  = BM / IN
	branch-miss-ratio = BM / BI

	print branch-rate
	print branch-miss-rate
	print branch-miss-ratio
}
