#!/bin/bash

#LDFLAGS=-static
set -x

NOS="NO_LIBPERL=1 NO_LIBPYTHON=1 NO_NEWT=1 NO_SLANG=1 NO_GTK2=1
NO_DEMANGLE=1 NO_LIBELF=1 NO_LIBUNWIND=1 NO_BACKTRACE=1
NO_LIBNUMA=1 NO_LIBAUDIT=1 NO_LIBBIONIC=1
NO_LIBDW_DWARF_UNWIND=1 NO_AUXTRACE=1 NO_LIBBPF=1
NO_LIBCRYPTO=1 NO_SDT=1 NO_JVMTI=1 NO_JVMTI_CMLR=1 NO_LIBZSTD=1
NO_LIBCAP=1 NO_SYSCALL_TABLE=1 NO_LIBBABELTRACE=1 NO_DWARF=1
NO_PERF_READ_VDSO32=1 NO_PERF_READ_VDSOX32=1 NO_ZLIB=1 NO_LZMA=1
NO_AUXTRACE=1 NO_AIO=1 NO_LIBZSTD=1 NO_SYSCALL_TABLE=1"

make clean
make $NOS $1
